modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bf_biomes"
version="0.0.1"
displayName="BlockFactory's Biomes"
displayURL="https://blockfactory.studio"
credits="Created by Furti_Two and Leroidesafk for Minecraft Java"
authors="BlockFactory, Furti_Two, Leroidesafk"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bf_biomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.bf_biomes]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

