modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bf_biomes"
version="1.0.0"
displayName="BlockFactory's Biomes"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="furti, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bf_biomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.bf_biomes]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

