
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.unusual.blockfactorysbiomes.init;

import net.unusual.blockfactorysbiomes.BfBiomesMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

public class BfBiomesModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, BfBiomesMod.MODID);
	public static final RegistryObject<CreativeModeTab> BLOCK_FACTORYS_BIOMES_TAB = REGISTRY.register("block_factorys_biomes_tab",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.bf_biomes.block_factorys_biomes_tab")).icon(() -> new ItemStack(BfBiomesModBlocks.COCONUT_TRUNK.get())).displayItems((parameters, tabData) -> {
				tabData.accept(BfBiomesModItems.BUG_NET.get());
				tabData.accept(BfBiomesModItems.COPPER_HELMET.get());
				tabData.accept(BfBiomesModItems.COPPER_CHESTPLATE.get());
				tabData.accept(BfBiomesModItems.COPPER_LEGGINGS.get());
				tabData.accept(BfBiomesModItems.COPPER_BOOTS.get());
				tabData.accept(BfBiomesModItems.BLUE_BUTTERFLY.get());
				tabData.accept(BfBiomesModItems.COPPER_PICKAXE.get());
				tabData.accept(BfBiomesModItems.GREEN_BUTTERFLY.get());
				tabData.accept(BfBiomesModItems.COPPER_AXE.get());
				tabData.accept(BfBiomesModItems.PINK_BUTTERFLY.get());
				tabData.accept(BfBiomesModItems.COPPER_SWORD.get());
				tabData.accept(BfBiomesModItems.ORANGE_BUTTERFLY.get());
				tabData.accept(BfBiomesModItems.COPPER_SHOVEL.get());
				tabData.accept(BfBiomesModItems.FIRE_FLY_ITEM.get());
				tabData.accept(BfBiomesModItems.COPPER_HOE.get());
				tabData.accept(BfBiomesModBlocks.COCONUT.get().asItem());
				tabData.accept(BfBiomesModItems.COCONUT_ITEM.get());
				tabData.accept(BfBiomesModItems.OPENED_COCONUT.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_SAPLING.get().asItem());
				tabData.accept(BfBiomesModBlocks.DEAD_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.TALL_DEAD_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.DRIED_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.TALL_DRIED_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.BUSHY_COCONUT_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.HANGING_COCONUT_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.FIREFLY_JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_BUSH.get().asItem());
				tabData.accept(BfBiomesModBlocks.BLUE_BUTTERFLY_JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.GREEN_BUTTERFLY_JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.PINK_BUTTERFLY_JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_COCONUT_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.ORANGE_BUTTERFLY_JAR.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_COCONUT_LOG.get().asItem());
				tabData.accept(BfBiomesModItems.RAW_DEER_BEEF.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_TRUNK.get().asItem());
				tabData.accept(BfBiomesModItems.COOKED_DEER_BEEF.get());
				tabData.accept(BfBiomesModBlocks.FALLEN_COCONUT_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_OVERGROWN_COCONUT_LOG.get().asItem());
				tabData.accept(BfBiomesModItems.DEER_HORN.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_LOG_PILE.get().asItem());
				tabData.accept(BfBiomesModItems.OSTRICH_EGG.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_PLANKS.get().asItem());
				tabData.accept(BfBiomesModItems.FRIED_EGG.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_STAIRS.get().asItem());
				tabData.accept(BfBiomesModItems.OSTRICH_SPAWN_EGG.get());
				tabData.accept(BfBiomesModBlocks.COCONUT_SLAB.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_FENCE.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_FENCE_GATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_PRESSURE_PLATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_BUTTON.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_DOOR.get().asItem());
				tabData.accept(BfBiomesModBlocks.COCONUT_TRAPDOOR.get().asItem());
				tabData.accept(BfBiomesModBlocks.LONG_SHELL.get().asItem());
				tabData.accept(BfBiomesModBlocks.ROUND_SHELL.get().asItem());
				tabData.accept(BfBiomesModBlocks.ZIGAG_SHELL.get().asItem());
				tabData.accept(BfBiomesModBlocks.BLUE_LION_PAW_SEASHELL.get().asItem());
				tabData.accept(BfBiomesModBlocks.PINK_LION_PAW_SEASHEL.get().asItem());
				tabData.accept(BfBiomesModBlocks.STARFISH.get().asItem());
				tabData.accept(BfBiomesModItems.CRAB_SPAWN_EGG.get());
				tabData.accept(BfBiomesModItems.RAW_CRAB_MEAT.get());
				tabData.accept(BfBiomesModItems.COOKED_CRAB_MEAT.get());
				tabData.accept(BfBiomesModBlocks.FALLEN_COCONUT_LEAVES.get().asItem());
				tabData.accept(BfBiomesModItems.FIREFLY_SPAWN_EGG.get());
				tabData.accept(BfBiomesModBlocks.RED_AUTUMN_GRASS.get().asItem());
				tabData.accept(BfBiomesModItems.MAPLE_SYRUP.get());
				tabData.accept(BfBiomesModBlocks.MAPLE_SAPLING.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.TALL_MAPLE_GRASS.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.BUSHY_MAPLE_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_BUSH.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_MAPLE_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_MAPLE_BRANCH.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.DRIPING_MAPLE_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_MAPLE_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_MAPLE_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_TRUNK.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_MAPLE_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_OVERGROWN_MAPLE_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_LOG_PILE.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_PLANKS.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_STAIRS.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_SLAB.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_FENCE.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_FENCE_GATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_PRESSURE_PLATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_BUTTON.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_DOOR.get().asItem());
				tabData.accept(BfBiomesModBlocks.MAPLE_TRAPDOOR.get().asItem());
				tabData.accept(BfBiomesModItems.SQUIRREL_SPAWN_EGG.get());
				tabData.accept(BfBiomesModItems.DEER_SPAWN_EGG.get());
				tabData.accept(BfBiomesModItems.BUTTERFLY_SPAWN_EGG.get());
				tabData.accept(BfBiomesModBlocks.DRY_SOIL.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_SAPLING.get().asItem());
				tabData.accept(BfBiomesModBlocks.PRICKLY_CACTUS.get().asItem());
				tabData.accept(BfBiomesModBlocks.FLOWERING_URCHIN_CACTUS.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.BUSHY_BAOBAB_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_BUSH.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_BAOBAB_WOOD.get().asItem());
				tabData.accept(BfBiomesModBlocks.STRIPPED_BAOBAB_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_TRUNK.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_BAOBAB_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_OVERGROWN_BAOBAB_LOG.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_LOG_PILE.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_PLANKS.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_STAIRS.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_SLAB.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_FENCE.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_FENCE_GATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_PRESSURE_PLATE.get().asItem());
				tabData.accept(BfBiomesModBlocks.DAISY.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_BUTTON.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_DOOR.get().asItem());
				tabData.accept(BfBiomesModBlocks.BAOBAB_TRAPDOOR.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_BAOBAB_LEAVES.get().asItem());
				tabData.accept(BfBiomesModBlocks.FALLEN_BAOBAB_BRANCH.get().asItem());
				tabData.accept(BfBiomesModItems.DEER_BEEF.get());
				tabData.accept(BfBiomesModItems.FRIED_OSTRICH_EGG.get());
				tabData.accept(BfBiomesModItems.CRAB_SANDWICH.get());
			})

					.build());
}
